# docker-compose.yml

services:
  react-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # 1) Monte tout le projet hôte (incluant node_modules existant) dans /app
      - .:/app
      # 2) Monte un volume anonyme pour /app/node_modules,
      #    afin de préserver les modules installés dans l'image
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
