# Utilise une image officielle de Node.js comme image de base
FROM node:18-alpine

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers de dépendances
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste des fichiers de l'application
COPY . .

# Expose le port sur lequel l'application sera accessible
EXPOSE 5000

# Démarre l'application
CMD ["npm", "start"]
