name: Deploy React App to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2 with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          WORK_DIR: ${{ secrets.WORK_DIR }}
          MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd "$WORK_DIR"
            echo "Pulling latest code..."
            git pull origin "$MAIN_BRANCH"

            echo "Stopping containers..."
            docker-compose -f docker-compose.yaml down --remove-orphans

            echo "Removing containers..."
            docker-compose -f docker-compose.yaml rm -f

            echo "Removing unused images..."
            docker image prune -af

            echo "Rebuilding and starting containers..."
            docker-compose -f docker-compose.yaml up -d --build
          EOF

      - name: Clean up SSH keys
        run: rm -rf ~/.ssh
